act_fn: !!python/name:torch.nn.modules.activation.SELU ''
beta: 1.0
config_lr_scheduler:
  factor: 0.4
  min_lr: 1.0e-09
  mode: min
  patience: 5
  threshold: 0.001
config_optimizer:
  betas: !!python/tuple
  - 0.9
  - 0.999
  lr: 0.00067
  weight_decay: 4.0e-05
dropout: 0.42
input_dim: 9
latent_dim: 3
lr_scheduler: !!python/name:torch.optim.lr_scheduler.ReduceLROnPlateau ''
monitor: train_loss
noise: null
noise_level: 1.0e-06
optimizer: !!python/name:torch.optim.adamw.AdamW ''
scale_factor:
- 0.5
